version: 2.1

orbs:
  helm: banzaicloud/helm@0.0.6
  helm2: banzaicloud/helm@0.0.5

helm-repositories: &helm_repositories
  - run: helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master
  - run: helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com
  - run: helm repo add rimusz https://charts.rimusz.net

workflows:
  version: 2
  static-checks:
    jobs:
      - helm2/lint-chart:
          name: Lint (Helm 2)
          charts-dir: '.'
          add-extra-repositories: *helm_repositories
          filters:
            tags:
              ignore: /.*/
  helm-3-lint:
    jobs:
      - helm/lint-chart:
          name: Lint (Helm 3)
          charts-dir: '.'
          add-extra-repositories: *helm_repositories
          filters:
            tags:
              ignore: /.*/
  release:
    jobs:
      - helm/publish-chart:
          context: helm
          charts-dir: '.'
          add-extra-repositories: *helm_repositories
          filters:
            tags:
              only: /\S+\/\d+.\d+.\d+/
            branches:
              ignore: /.*/
